services:
  - type: web
    name: terrys-table
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4
    healthCheckPath: /healthz
    envVars:
      - key: YAHOO_CLIENT_ID
        sync: false
      - key: YAHOO_CLIENT_SECRET
        sync: false
      - key: YAHOO_REDIRECT_URI
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: YAHOO_REFRESH_TOKEN
        sync: false
      - key: YAHOO_LEAGUE_KEY
        sync: false
